<?php

namespace SNT\ReservationBundle\Repository;

/**
 * quartierRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quartierRepository extends \Doctrine\ORM\EntityRepository
{
}
