<?php

namespace SNT\ReservationBundle\Repository;

/**
 * txtContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class txtContratRepository extends \Doctrine\ORM\EntityRepository
{
}
