<?php

namespace Proxies\__CG__\SNT\ReservationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bien extends \SNT\ReservationBundle\Entity\Bien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nomBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'prixLoc', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'dateAjout', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'surface', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreChambre', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreEtage', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreSalon', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreSallebain', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'balcon', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'meuble', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'parking', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'disponibilite', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'adresse', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'proprietaire', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'sousBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'typeBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'quartier'];
        }

        return ['__isInitialized__', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nomBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'prixLoc', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'dateAjout', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'surface', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreChambre', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreEtage', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreSalon', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'nbreSallebain', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'balcon', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'meuble', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'parking', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'disponibilite', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'adresse', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'proprietaire', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'sousBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'typeBien', '' . "\0" . 'SNT\\ReservationBundle\\Entity\\Bien' . "\0" . 'quartier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixLoc($prixLoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixLoc', [$prixLoc]);

        return parent::setPrixLoc($prixLoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixLoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixLoc', []);

        return parent::getPrixLoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjout($dateAjout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjout', [$dateAjout]);

        return parent::setDateAjout($dateAjout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjout', []);

        return parent::getDateAjout();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface($surface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', [$surface]);

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', []);

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreChambre($nbreChambre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreChambre', [$nbreChambre]);

        return parent::setNbreChambre($nbreChambre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreChambre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreChambre', []);

        return parent::getNbreChambre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreEtage($nbreEtage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreEtage', [$nbreEtage]);

        return parent::setNbreEtage($nbreEtage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreEtage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreEtage', []);

        return parent::getNbreEtage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreSalon($nbreSalon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreSalon', [$nbreSalon]);

        return parent::setNbreSalon($nbreSalon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreSalon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreSalon', []);

        return parent::getNbreSalon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreSallebain($nbreSallebain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreSallebain', [$nbreSallebain]);

        return parent::setNbreSallebain($nbreSallebain);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreSallebain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreSallebain', []);

        return parent::getNbreSallebain();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalcon($balcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalcon', [$balcon]);

        return parent::setBalcon($balcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalcon', []);

        return parent::getBalcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeuble($meuble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeuble', [$meuble]);

        return parent::setMeuble($meuble);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeuble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeuble', []);

        return parent::getMeuble();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', [$parking]);

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', []);

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilite($disponibilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilite', [$disponibilite]);

        return parent::setDisponibilite($disponibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilite', []);

        return parent::getDisponibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietaire(\SNT\ReservationBundle\Entity\proprietaire $proprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietaire', [$proprietaire]);

        return parent::setProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousBien(\SNT\ReservationBundle\Entity\Bien $sousBien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousBien', [$sousBien]);

        return parent::setSousBien($sousBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousBien', []);

        return parent::getSousBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeBien(\SNT\ReservationBundle\Entity\typeBien $typeBien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeBien', [$typeBien]);

        return parent::setTypeBien($typeBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeBien', []);

        return parent::getTypeBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuartier(\SNT\ReservationBundle\Entity\quartier $quartier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuartier', [$quartier]);

        return parent::setQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuartier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuartier', []);

        return parent::getQuartier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomBien($nomBien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomBien', [$nomBien]);

        return parent::setNomBien($nomBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomBien', []);

        return parent::getNomBien();
    }

}
